# Generated by Django 2.2.5 on 2019-09-18 16:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('case_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(60)])),
                ('thickness', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)])),
                ('lug_width', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(30)])),
                ('lug_to_lug', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(70)])),
                ('water_resistance', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)])),
                ('manufacture_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1700)])),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('availability', models.BooleanField(default=True)),
                ('box_papers', models.CharField(max_length=100)),
                ('strap', models.CharField(blank=True, max_length=100, null=True)),
                ('functions', models.CharField(blank=True, max_length=100, null=True)),
                ('movement', models.CharField(choices=[('automatic', 'automatic'), ('manual', 'manual'), ('quartz', 'quartz')], default=False, max_length=12)),
                ('payment', models.CharField(choices=[('paypal', 'paypal'), ('credit_card', 'credit card'), ('cash', 'cash'), ('knet', 'knet')], default='cash', max_length=10)),
                ('delivery', models.CharField(choices=[('in_person', 'in person'), ('DHL', 'DHL'), ('FEDEX', 'FEDEX'), ('EMS', 'EMS'), ('driver_delivery', 'driver delivery')], default='in_person', max_length=20)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
                ('watches', models.ManyToManyField(to='api.Watch')),
            ],
        ),
    ]
