# Generated by Django 2.1 on 2019-09-19 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190919_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='watch',
            name='functions',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watch',
            name='manufacture_year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1700)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watch',
            name='water_resistance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)]),
            preserve_default=False,
        ),
    ]
