# Generated by Django 2.1 on 2019-09-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190922_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.PositiveIntegerField(),
        ),
    ]
