# Generated by Django 2.1 on 2019-09-22 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190922_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
