# Generated by Django 2.1 on 2019-09-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190922_1313'),
        ('api', '0004_auto_20190922_0747'),
    ]

    operations = [
    ]
