# Generated by Django 2.1 on 2019-09-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20190923_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='watches',
            field=models.ManyToManyField(related_name='carts', to='api.Watch'),
        ),
    ]
