# Generated by Django 2.2.5 on 2019-09-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190924_1630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.AlterField(
            model_name='watch',
            name='brand',
            field=models.CharField(max_length=30),
        ),
    ]
