# Generated by Django 2.2.5 on 2019-09-25 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190924_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='functions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='watch',
            name='manufacture_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1700)]),
        ),
    ]
