# Generated by Django 2.1 on 2019-09-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190925_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, choices=[('Kuwait', 'Kuwait'), ('Oman', 'Oman'), ('UAE', 'UAE'), ('KSA', 'KSA'), ('Bahrain', 'Bahrain'), ('Qatar', 'Qatar'), ('other', 'other')], default='Kuwait', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='governate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street_line1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street_line2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
